{% set name = "line_profiler" %}
{% set version = "4.1.0" %}
{% set checksum = "dd93444373231e624aee354ceaf29ac35889660923cbf912124c9872cf410127" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script:
    - export CMAKE_OSX_ARCHITECTURES="arm64"  # [osx and arm64]
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kernprof = kernprof:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - scikit-build                           # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - cython
    - scikit-build >=0.17
  run:
    - python
    - ipython >=0.13
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - kernprof
    - line_profiler

  commands:
    - kernprof --help
    - python -m kernprof --help

about:
  home: https://github.com/pyutils/line_profiler
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A module for monitoring memory usage of a python program
  dev_url: https://github.com/pyutils/line_profiler
  doc_url: https://github.com/pyutils/line_profiler

extra:
  recipe-maintainers:
    - jakirkham
    - grlee77
