{% set name = "line_profiler" %}
{% set version = "3.3.1" %}
{% set checksum = "6e2fb792ca022f900f374f9659fd3e7c530cd4df7d3b7e84be889093b487639f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script:
    # We can't use CMAKE_GENERATOR implicitly via conda_build_config.yaml, yet,
    # due to https://github.com/AnacondaRecipes/aggregate/pull/182
    - set "CMAKE_GENERATOR={{ CMAKE_GENERATOR }}"  # [win]
    - export CMAKE_GENERATOR=Ninja  # [not (win or (osx and arm64))]
    - {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kernprof = kernprof:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - cmake
    - ninja
  host:
    - python
    - pip
    - cython
    - scikit-build
  run:
    - python
    - ipython >=0.13

test:
  imports:
    - kernprof
    - line_profiler

  commands:
    - kernprof --help
    - python -m kernprof --help

about:
  home: https://github.com/pyutils/line_profiler
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A module for monitoring memory usage of a python program
  dev_url: https://github.com/pyutils/line_profiler
  doc_url: https://github.com/pyutils/line_profiler

extra:
  recipe-maintainers:
    - jakirkham
    - koverholt
    - grlee77
