{% set name = "line_profiler" %}
{% set version = "3.0.2" %}
{% set checksum = "7218ad6bd81f8649b211974bf108933910f016d66b49651effe7bbf63667d141" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: 0
  script:
    # Remove Python 3.7-incompatible cython-generated _line_profiler.c
    # Cython was added to the host deps so this can be regenerated.
    - del _line_profiler.c  # [win]
    - rm _line_profiler.c  # [not win]
    - "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - kernprof = kernprof:main

requirements:
  build:
    - {{ compiler("c") }}

  host:
    - python
    - pip
    - cython

  run:
    - python
    - ipython >=0.13

test:
  imports:
    - kernprof
    - line_profiler
    - line_profiler_py35  # [py>34]

  commands:
    - kernprof --help
    - python -m kernprof --help
    - python -m line_profiler --help

about:
  home: https://github.com/rkern/line_profiler
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A module for monitoring memory usage of a python program
  dev_url: https://github.com/rkern/line_profiler
  doc_url: https://github.com/rkern/line_profiler

extra:
  recipe-maintainers:
    - jakirkham
    - koverholt
    - grlee77
