# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fr2FPVoTaEx237iVVo1GpVu6LGIhJNLNrTMi2U+RnSirdfkiBASkN8yqksQsWcQmTpZlbOHz3lHaBbj4ymra87/Neeztdc2LlgEoqJtMVUQVtko+L1XbBJBFNdq6z/fTJ6F5WHIr86oQdpkE0yV8WDVFUkGb2kG7ViKIZISxHyHXIVNriWENowNAR+xKBNGmFo5nzZ3gqfj3D758CwkIlU9Kl2cZA6nkO3BiBokQ/fGGb2dr5hFYqUJ5SE0adcmC76Oli58JXmUaz7ci8F1mRjDtpVk3sXp6aAtLUr0RVcgjBuTDqvNLl4K9frOljWjH/gAURDdWI+Hj03ZJZcXeL6tjiveDvz+fWTT3rU5sLJ63mwFo8nHqUcirP0tcPOSkenK86sQfrcdnmp1/5er6ede4tvvEMMVr1JtiUdiop0QHLdtJqpgFQRPO+4Dws+u4RKW3gwiXnw5vkYWtTdXHUUiANcuhlD0YxKPTOx6SvflV+FV9SpYwJ7cInr1G0ee0VHp21PNe1qAlxNlU6tYVmhDx0EqwOrtZx6Vm85k2ZbACLhc7cTQYHdTzBv4wX648/LZMhjljChQCHe1TNLa8RdP+igfG92FJ8gao6WFCkarSzA/VaG4GhnB97huHrmTVVoCzYSOPo6sMIEIasqEBoT4BfHpavkSrlqczBKUPj+Q="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  # Build, store the exit status, and exit.
  # Travis will muck with `$?` so we need to do this.
  # See the docs for details.
  #
  # https://docs.travis-ci.com/user/customizing-the-build/#Note-on-%24%3F
  #
  - conda build ./recipe;
    export CONDA_BUILD_STATUS=$?;
    exit $CONDA_BUILD_STATUS

  # Upload the package if the build doesn't fail.
  - if [[ $CONDA_BUILD_STATUS == 0 ]]; then
        ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main ;
    fi
